version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/next" 
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/strapi" 
    schedule:
      interval: "daily"
