version: '3.8'

services:
  next:
    container_name: next
    image: luuppi.azurecr.io/next:latest
    restart: unless-stopped
    env_file: .env.local
    environment:
      - REDIS_HOST=redisDB
    ports:
      - '3000:3000'
    depends_on:
      - redisDB
    networks:
      - weba-network

  redisDB:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - weba-network

#
# External network handled by luuppi-proxy
# https://github.com/luuppiry/luuppi-proxy
#
networks:
  weba-network:
    external: true
