version: '3.8'

services:
  app:
    container_name: next
    build: .
    image: next:latest
    restart: unless-stopped
    env_file: .env.local
    ports:
      - '3000:3000'
    depends_on:
      - redisDB
    networks:
      - next-redis

  redisDB:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - next-redis

networks:
  next-redis:
    driver: bridge
