name: Build and Deploy

on:
    push:
        branches: ['main']

jobs:
    changes:
        name: Check for changes
        runs-on: ubuntu-latest
        outputs:
            strapi: ${{ steps.filter.outputs.strapi }}
            next: ${{ steps.filter.outputs.next }}
        steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  filters: |
                      strapi:
                        - 'strapi/**'
                      next:
                        - 'next/**'

    strapi:
        needs: changes
        if: ${{ needs.changes.outputs.strapi == 'true' }}
        name: Build and Deploy Strapi
        timeout-minutes: 15
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Backup Strapi
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd luuppi-next/strapi
                      docker compose exec -T strapi sh -c 'npm run strapi export -- --no-encrypt --file backup'
                      docker cp strapi:/opt/app/backup.tar.gz backup-$(date +%Y-%m-%d-%H-%M-%S).tar.gz
                      docker compose exec -T strapi sh -c 'rm backup.tar.gz'

            - name: Install dependencies
              run: npm install
              working-directory: ./strapi

            - name: Build Strapi
              run: npm run build
              working-directory: ./strapi

            - name: Deploy Strapi
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd luuppi-next
                      git pull
                      cd strapi
                      docker build -t strapi .
                      docker compose down
                      docker compose up -d

    next:
        needs: [changes, strapi]
        if: |
            always() &&
            needs.changes.outputs.next == 'true' &&
            (needs.strapi.result == 'success' || needs.strapi.result == 'skipped')
        name: Build and Deploy Next.js
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install
              working-directory: ./next

            - name: Add Next.js environment variables
              run: |
                  touch .env.local
                  echo NEXT_PUBLIC_STRAPI_BASE_URL=https://${{ secrets.CMS_HOST }} >> .env.local
                  echo NEXT_PUBLIC_BASE_URL=https://${{ secrets.BASE_HOST }} >> .env.local
              working-directory: ./next

            - name: Build Next.js
              run: npm run build
              working-directory: ./next

            - name: Deploy Next.js
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd luuppi-next
                      git pull
                      cd next
                      docker build -t next:latest .
                      docker compose down
                      docker compose up -d
